### ISSUE TITLE
hello :)

### ISSUE THREAD

**Issue by Bluscream** [ameshkov/test#1]
May i ask what your AG forum account name is ?

I can't seem to find you: https://forum.adguard.com/index.php?members/&type=staff

**Comment by ameshkov** [comment]
avatar :)

**Comment by Bluscream** [comment]
Ohh so that's you. Thanks a lot :D

**Comment by ameshkov** [comment]
>
> Can we aim for 3pm/11am?


Yes, that'd be awesome!

 What's the best way to reach you?


Any of these:

Telegram: @AMeshkov
Phone: +1 (508) 964-0341

--
Best regards,
Andrey Meshkov

CTO at AdGuard <https://adguard.com/>
am@adguard.com
